[global]
    showWarningOnDirectExecution = true

[client]
    showErrorDetails = true
    showSidebarNavigation = false

[theme]
    base="light"
    primaryColor="#4285f4"
    secondaryBackgroundColor="#e8eaed"
    textColor="#202124"

[server]
    runOnSave = false
    port = 8501
    enableCORS = true
    enableWebsocketCompression = true
    enableStaticServing = true
